-- Thai names for ingredients, dishes and sauces. The app shows the Thai
-- name when switched to ไทย (falling back to English when empty), and
-- both names can be edited per item in the app.
-- Run once in the Supabase SQL editor.

alter table public.ingredients add column if not exists name_th text;
alter table public.dishes add column if not exists name_th text;
alter table public.sauces add column if not exists name_th text;

-- ---------- ingredients ----------
update public.ingredients as i set name_th = v.th
from (values
  ('Chicken thigh', 'สะโพกไก่'),
  ('Chicken breast', 'อกไก่'),
  ('Whole chicken', 'ไก่ทั้งตัว'),
  ('Chicken wings', 'ปีกไก่'),
  ('Pork mince', 'หมูสับ'),
  ('Pork shoulder', 'ไหล่หมู'),
  ('Pork belly', 'หมูสามชั้น'),
  ('Pork bones (stock)', 'กระดูกหมู (ต้มซุป)'),
  ('Beef (rump)', 'เนื้อวัว (สะโพก)'),
  ('Prawns', 'กุ้ง'),
  ('Squid', 'ปลาหมึก'),
  ('White fish fillet', 'เนื้อปลาขาว'),
  ('Fish balls', 'ลูกชิ้นปลา'),
  ('Pork balls', 'ลูกชิ้นหมู'),
  ('Eggs', 'ไข่ไก่'),
  ('Firm tofu', 'เต้าหู้แข็ง'),
  ('Jasmine rice', 'ข้าวหอมมะลิ'),
  ('Sticky rice (glutinous)', 'ข้าวเหนียว'),
  ('Thin rice noodles (sen lek)', 'เส้นเล็ก'),
  ('Wide rice noodles (sen yai)', 'เส้นใหญ่'),
  ('Kelp noodles', 'เส้นแก้วสาหร่าย'),
  ('Glass noodles', 'วุ้นเส้น'),
  ('Egg noodles', 'บะหมี่'),
  ('Garlic', 'กระเทียม'),
  ('Red chilli', 'พริกแดง'),
  ('Bird''s eye chilli', 'พริกขี้หนู'),
  ('Dried chilli', 'พริกแห้ง'),
  ('Brown onion', 'หอมหัวใหญ่'),
  ('Shallots', 'หอมแดง'),
  ('Spring onion', 'ต้นหอม'),
  ('Coriander', 'ผักชี'),
  ('Holy basil', 'กะเพรา'),
  ('Thai basil', 'โหระพา'),
  ('Gai lan (Chinese broccoli)', 'คะน้า'),
  ('Carrot', 'แครอท'),
  ('Cabbage', 'กะหล่ำปลี'),
  ('Bean sprouts', 'ถั่วงอก'),
  ('Tomato', 'มะเขือเทศ'),
  ('Mushrooms', 'เห็ด'),
  ('Baby corn', 'ข้าวโพดอ่อน'),
  ('Snake beans', 'ถั่วฝักยาว'),
  ('Bamboo shoots', 'หน่อไม้'),
  ('Lemongrass', 'ตะไคร้'),
  ('Galangal', 'ข่า'),
  ('Kaffir lime leaves', 'ใบมะกรูด'),
  ('Lime', 'มะนาว'),
  ('Ginger', 'ขิง'),
  ('Cucumber', 'แตงกวา'),
  ('Pickled mustard greens', 'ผักกาดดอง'),
  ('Pickled radish', 'หัวไชโป๊'),
  ('Mango', 'มะม่วง'),
  ('Durian (frozen)', 'ทุเรียน (แช่แข็ง)'),
  ('Longan', 'ลำไย'),
  ('Chrysanthemum flowers', 'ดอกเก๊กฮวย'),
  ('Vegetable oil', 'น้ำมันพืช'),
  ('Sesame oil', 'น้ำมันงา'),
  ('Fish sauce', 'น้ำปลา'),
  ('Light soy sauce', 'ซีอิ๊วขาว'),
  ('Dark soy sauce', 'ซีอิ๊วดำ'),
  ('Sweet soy sauce', 'ซีอิ๊วหวาน'),
  ('Black soy sauce', 'ซีอิ๊วดำเข้ม'),
  ('Oyster sauce', 'ซอสหอยนางรม'),
  ('Sriracha chilli sauce', 'ซอสศรีราชา'),
  ('White vinegar', 'น้ำส้มสายชู'),
  ('Evaporated milk', 'นมข้นจืด'),
  ('Coconut milk', 'กะทิ'),
  ('Coconut cream', 'หัวกะทิ'),
  ('Sukiyaki sauce', 'น้ำจิ้มสุกี้'),
  ('Red soda syrup (sala)', 'น้ำหวานกลิ่นสละ'),
  ('Full cream milk', 'นมสด'),
  ('Red curry paste', 'พริกแกงแดง'),
  ('Tom yum paste', 'น้ำพริกต้มยำ'),
  ('Chilli jam (nam prik pao)', 'น้ำพริกเผา'),
  ('Tamarind paste', 'มะขามเปียก'),
  ('Shrimp paste', 'กะปิ'),
  ('Condensed milk', 'นมข้นหวาน'),
  ('Palm sugar', 'น้ำตาลปี๊บ'),
  ('White sugar', 'น้ำตาลทราย'),
  ('Salt', 'เกลือ'),
  ('White pepper', 'พริกไทยขาว'),
  ('Black pepper', 'พริกไทยดำ'),
  ('Chicken stock powder', 'ผงปรุงรสไก่'),
  ('Rice flour', 'แป้งข้าวเจ้า'),
  ('Tapioca flour', 'แป้งมันสำปะหลัง'),
  ('Puff pastry (curry puff)', 'แป้งพัฟ (กะหรี่ปั๊บ)'),
  ('Spring roll wrappers', 'แผ่นปอเปี๊ยะ'),
  ('Crushed peanuts', 'ถั่วลิสงบด'),
  ('Dried shrimp', 'กุ้งแห้ง'),
  ('Ice', 'น้ำแข็ง'),
  ('Thai tea leaves', 'ใบชาไทย'),
  ('Black tea leaves', 'ใบชาดำ'),
  ('O-liang coffee powder', 'ผงกาแฟโอเลี้ยง')
) as v(en, th)
where i.name = v.en and (i.name_th is null or i.name_th = '');

-- ---------- dishes ----------
update public.dishes as d set name_th = v.th
from (values
  ('Pad Kra Pow on Rice', 'กะเพราราดข้าว'),
  ('Thai Fried Rice', 'ข้าวผัด'),
  ('Spicy Basil Fried Rice', 'ข้าวผัดกะเพรา'),
  ('Tom Yum Fried Rice', 'ข้าวผัดต้มยำ'),
  ('Chili Jam Stir Fry on Rice', 'ผัดน้ำพริกเผาราดข้าว'),
  ('Garlic & Pepper Stir Fry on Rice', 'ผัดกระเทียมพริกไทยราดข้าว'),
  ('Red Curry Paste Stir Fried', 'ผัดพริกแกง'),
  ('Gai-Lan (Kana) Oyster Sauce over Rice', 'คะน้าน้ำมันหอยราดข้าว'),
  ('Chilli Salt Stir-Fry on Rice', 'ผัดพริกเกลือราดข้าว'),
  ('Pad See Eiw', 'ผัดซีอิ๊ว'),
  ('Pad Thai', 'ผัดไทย'),
  ('Pad Kee Mao with Rice Noodles', 'ผัดขี้เมา'),
  ('Sen Kaeaw Salad – Kelp Noodle', 'ยำเส้นแก้ว'),
  ('Dry Sukiyaki Kelp Noodles', 'สุกี้แห้งเส้นแก้ว'),
  ('Tum Sen Lek – Thin Rice Noodle Salad', 'ตำเส้นเล็ก'),
  ('Clear Noodle Soup', 'ก๋วยเตี๋ยวน้ำใส'),
  ('Creamy Tom Yum Noodles', 'ก๋วยเตี๋ยวต้มยำน้ำข้น'),
  ('Spicy and Sour Soup', 'ก๋วยเตี๋ยวต้มแซ่บ'),
  ('Boat Noodles', 'ก๋วยเตี๋ยวเรือ'),
  ('Pink Noodle Sauce', 'เย็นตาโฟ'),
  ('Dry Noodles with Black Soy Sauce', 'ก๋วยเตี๋ยวแห้งซีอิ๊วดำ'),
  ('Moo Ping – Pork Skewers', 'หมูปิ้ง'),
  ('Set Moo Ping (Pork Skewers)', 'ชุดหมูปิ้ง'),
  ('Thai Fish Cake (1 pc)', 'ทอดมันปลา (1 ชิ้น)'),
  ('Spring Roll (1 pc)', 'ปอเปี๊ยะทอด (1 ชิ้น)'),
  ('Sour Pork (1 pc)', 'แหนม (1 ชิ้น)'),
  ('Sour Pork (3 pcs)', 'แหนม (3 ชิ้น)'),
  ('Chicken Dim Sim (4 pcs)', 'ขนมจีบไก่ (4 ชิ้น)'),
  ('Chicken Dim Sim (1 pc)', 'ขนมจีบไก่ (1 ชิ้น)'),
  ('Chicken Wing Zap', 'ปีกไก่แซ่บ'),
  ('Curry Puff', 'กะหรี่ปั๊บ'),
  ('Thai Sausage', 'ไส้กรอกอีสาน'),
  ('Thai Fried Rice (Vegan)', 'ข้าวผัด (วีแกน)'),
  ('Garlic and Pepper (Vegan)', 'ผัดกระเทียมพริกไทย (วีแกน)'),
  ('Pad Ka Praw (Vegan)', 'ผัดกะเพรา (วีแกน)'),
  ('Spicy Basil Fried Rice (Vegan)', 'ข้าวผัดกะเพรา (วีแกน)'),
  ('Thai Salt and Chili (Vegan)', 'ผัดพริกเกลือ (วีแกน)'),
  ('Chili Jam Stir Fried (Vegan)', 'ผัดน้ำพริกเผา (วีแกน)'),
  ('Pad Kee Mao (Vegan)', 'ผัดขี้เมา (วีแกน)'),
  ('Red Curry Stir Fried (Vegan)', 'ผัดพริกแกง (วีแกน)'),
  ('Gai-Lan (Kana) Oyster Sauce (Vegan)', 'คะน้าน้ำมันหอย (วีแกน)'),
  ('Sen Keaw Salad (Vegan)', 'ยำเส้นแก้ว (วีแกน)'),
  ('Thai Fried Rice (GF)', 'ข้าวผัด (ปลอดกลูเตน)'),
  ('Garlic and Pepper (GF)', 'ผัดกระเทียมพริกไทย (ปลอดกลูเตน)'),
  ('Pad Ka Praw (GF)', 'ผัดกะเพรา (ปลอดกลูเตน)'),
  ('Spicy Basil Fried Rice (GF)', 'ข้าวผัดกะเพรา (ปลอดกลูเตน)'),
  ('Thai Salt and Chili (GF)', 'ผัดพริกเกลือ (ปลอดกลูเตน)'),
  ('Chili Jam Stir Fried (GF)', 'ผัดน้ำพริกเผา (ปลอดกลูเตน)'),
  ('Red Curry Paste Stir Fried (GF)', 'ผัดพริกแกง (ปลอดกลูเตน)'),
  ('Gai-Lan (Kana) Oyster Sauce (GF)', 'คะน้าน้ำมันหอย (ปลอดกลูเตน)'),
  ('Pad Kee Mao (GF)', 'ผัดขี้เมา (ปลอดกลูเตน)'),
  ('Sen Keaw Salad (GF)', 'ยำเส้นแก้ว (ปลอดกลูเตน)'),
  ('Dry Sukiyaki (GF)', 'สุกี้แห้ง (ปลอดกลูเตน)'),
  ('Tum Sen Lek Salad (GF)', 'ตำเส้นเล็ก (ปลอดกลูเตน)'),
  ('Thai Milk Tea', 'ชานมไทย'),
  ('Thai Black Tea', 'ชาดำ'),
  ('Thai Lemon Tea', 'ชามะนาว'),
  ('Chrysanthemum Tea', 'น้ำเก๊กฮวย'),
  ('Longan Juice', 'น้ำลำไย'),
  ('Pinky Milky', 'นมเย็น'),
  ('O-Liang Black Coffee', 'โอเลี้ยง'),
  ('Thai Red Soda', 'น้ำแดงโซดา'),
  ('Mango Sticky Rice', 'ข้าวเหนียวมะม่วง'),
  ('Durian', 'ทุเรียน'),
  ('Beef Jerky', 'เนื้อแดดเดียว'),
  ('Chilli Oil', 'น้ำมันพริก'),
  ('Crispy Pork Crackers', 'แคบหมู'),
  ('Jaew Bong', 'แจ่วบอง'),
  ('Mango Sweet & Sour', 'มะม่วงสามรส'),
  ('Nam Prik Namyoi', 'น้ำพริกน้ำย้อย'),
  ('Pork Jerky', 'หมูแดดเดียว'),
  ('Spicy Crispy Pork Cracker (Small)', 'แคบหมูรสเผ็ด (เล็ก)'),
  ('Thai Dip Seafood (Small)', 'น้ำจิ้มซีฟู้ด (เล็ก)'),
  ('Nam Prik Ari Mackerel Fish', 'น้ำพริกอารีย์ปลาทู'),
  ('Nam Prik Ari Pla Salid', 'น้ำพริกอารีย์ปลาสลิด'),
  ('Nam Prik Ari Seasonal Clam', 'น้ำพริกอารีย์หอย'),
  ('Nam Prik Ari Dried Shrimp', 'น้ำพริกอารีย์กุ้งแห้ง'),
  ('Hainanese Chicken', 'ข้าวมันไก่'),
  ('Spicy Bamboo Salad', 'ซุปหน่อไม้'),
  ('Pork Blood Soup', 'ต้มเลือดหมู'),
  ('Jasmine Rice', 'ข้าวสวย'),
  ('Sticky Rice', 'ข้าวเหนียว')
) as v(en, th)
where d.name = v.en and (d.name_th is null or d.name_th = '');
